---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30561  # Access via: http://192.168.1.69:30561

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      # Run on master (same node as Elasticsearch)
      nodeSelector:
        kubernetes.io/hostname: k8s-master

      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana-oss:8.11.0
          ports:
            - containerPort: 5601
          env:
            # Connect to Elasticsearch service
            - name: ELASTICSEARCH_HOSTS
              value: "http://elasticsearch:9200"

            # Reduce logging for performance
            - name: LOGGING_QUIET
              value: "true"

          resources:
            requests:
              memory: "300Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "400m"
